name: Node.js Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
        description: 'Node.js version'
        default: '14'
      working_directory:
        required: false
        type: string
        description: 'Working directory'
        default: '.'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.working_directory }}

      - name: Run tests
        run: npm test
        working-directory: ${{ inputs.working_directory }}
