name: Generate README

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq (YAML Processor)
        run: sudo snap install yq

      - name: Generate README
        run: |
          echo "# Repository Workflows and Actions" > README.md
          echo "## Workflows" >> README.md
          for file in .github/workflows/*.yml; do
            echo "### $(basename $file)" >> README.md
            echo '```yaml' >> README.md
      
            # Extracting and printing workflow name and description
            echo "Name: $(yq e '.name' $file)" >> README.md
            echo "Description: $(yq e '.on.workflow_call.inputs.description.default' $file)" >> README.md
            
            # Extracting inputs
            echo "\nInputs:" >> README.md
            yq e '.on.workflow_call.inputs.* | "Name: " + (. | path | .[-1]) + "\nDescription: " + .description + "\nType: " + .type + "\nDefault: " + .default' $file >> README.md
      
            # Extracting outputs
            echo "\nOutputs:" >> README.md
            yq e '.outputs.* | "Name: " + (. | path | .[-1]) + "\nDescription: " + .description' $file >> README.md
      
            # Extracting secrets
            echo "\nSecrets:" >> README.md
            yq e '.on.workflow_call.secrets.* | "Name: " + (. | path | .[-1]) + "\nDescription: " + .description' $file >> README.md
      
            echo '```' >> README.md
          done


      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Updated README with workflow details"
          git push
