name: Generate README

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq (YAML Processor)
        run: sudo snap install yq

      - name: Generate README
        run: |
          echo "# Repository Workflows and Actions" > README.md
          echo "## Workflows" >> README.md
          for file in .github/workflows/*.yml; do
            echo "### $(basename $file)" >> README.md
            echo '```yaml' >> README.md

            # Extracting and printing workflow name, description, type, and default values
            echo "Name: $(yq e '.name' $file)" >> README.md
            echo "Description: $(yq e '.on.workflow_call.inputs.description.default' $file)" >> README.md
            echo "Type: $(yq e '.on.workflow_call.inputs.type.default' $file)" >> README.md
            echo "Default: $(yq e '.on.workflow_call.inputs.default' $file)" >> README.md

            echo '```' >> README.md
          done

          echo "## Composite Actions" >> README.md
          for dir in actions/*; do
            if [ -d "$dir" ]; then
              echo "### $(basename $dir)" >> README.md
              for file in $dir/*.yml; do
                echo "#### $(basename $file)" >> README.md
                echo '```yaml' >> README.md
                # Add similar yq commands for composite actions if needed
                echo '```' >> README.md
              done
            fi
          done

      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Updated README with workflow details"
          git push
